on:
  push:
    branches:
      - main
      - experimental
  pull_request:
  release:
    types:
      - created

env:
  BRANCH_TAG: ${{ github.head_ref == 'experimental' && 'experimental' || '' }}

name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: make install
        run:  make install
      - name: lint
        run:  make lint
      - name: build
        run:  make build
      - name: Publish
        uses: menduz/oddish-action@master
        with:
          registry-url: "https://registry.npmjs.org"
          access: public
          custom-tag: ${{ env.BRANCH_TAG }}
          branch-to-custom-tag: ${{ env.BRANCH_TAG }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref }}
